### ISSUE TITLE
Problem handling an ipuz crossword.

### ISSUE THREAD

**Issue by JujuLand** [svisser/ipuz#2]
Hi, having installed crossword and ipuz-0.1.4, I tried to load an ipuz crossword file found on this page 
http://www.ipuz.org

Here is a sample Crossword in ipuz format:
{
    "version": "http://ipuz.org/v2",
    "kind": [ "http://ipuz.org/crossword#1" ],
    "dimensions": { "width": 3, "height": 3 },
    "puzzle": [ [ { "cell": 1, "style": { "shapebg": "circle" } }, 2, "#" ],
                [ 3, { "style": { "shapebg": "circle" } }, 4 ],
                [ null, 5, { "style": { "shapebg": "circle" } } ] ],
    "solution": [ [ "C", "A", "#" ],
                  [ "B", "O", "T" ],
                  [ null, "L", "O" ] ],
    "clues": { "Across": [ [ 1, "OR neighbor" ],
                           [ 3, "Droid" ],
                           [ 5, "Behold!" ] ],
               "Down": [ [ 1, "Trucker's radio" ],
                            [ 2, "MSN competitor" ],
                            [ 4, "A preposition" ] ] }
}
It fails with this error 

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ipuz-0.1.4-py2.7.egg/ipuz/core.py", line 53, in read
    validate_version("version", json_data["version"], IPUZ_VERSIONS)
  File "/usr/local/lib/python2.7/dist-packages/ipuz-0.1.4-py2.7.egg/ipuz/validators.py", line 100, in validate_version
    raise IPUZException("Unsupported version value found")
ipuz.exceptions.IPUZException: Unsupported version value found

When replacing v2 by v1, no more error.

My question is
Is  there a module corresponding to the v2 specifications ?

Thanks
A+

**Comment by svisser** [comment]
@JujuLand hi there, thanks for your issue!

Currently this Python package supports validating ipuz puzzles that match V1 of the ipuz specification.

I haven't worked on this for a while and it indeed doesn't support the changes made in V2 of the ipuz specification. So that's why it raises an error as it only knows about the elements included in V1 of the ipuz file format.

I'm not sure when I can get around to updating this package to include them. If you're interested, I'd be happy to merge a pull request that adds those changes.

**Comment by JujuLand** [comment]
Thanks for your answer.
I would be happy that my question can be transform as a request.
For now, is there a page which describe the v1 spécifications ?

Thanks
A+

**Comment by svisser** [comment]
Yeah, the http://www.ipuz.org website documents the ipuz file format.

It also shows the differences between V1 and V2.

These have been marked using green, orange and purple colors:

- This is an addition in 2.0 (green)
- This has been changed since 1.0 (orange)
- No change has been made, but it was moved in the spec (purple)

**Comment by rcoh** [comment]
FWIW, there are no changes in the `crossword` spec -- for crosswords it should be sufficient to just accept v2.

**Comment by svisser** [comment]
@JujuLand @rcoh I admit it has been a while but there is now version 1.0 of the `ipuz` library with support for ipuz v2 puzzles, thanks to @maiamcc :tada: https://pypi.org/project/ipuz/ If anything doesn't work, please let me know.
